name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # Use only Ubuntu for testing
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Modern Python versions only

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Python syntax
      run: |
        python -m py_compile examples/*.py
        find retire_cluster -name "*.py" -exec python -m py_compile {} \;
    
    - name: Test imports
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import examples.simple_main_server; print('✓ Main server imports successfully')"
        python -c "import examples.simple_worker_client; print('✓ Worker client imports successfully')"
    
    - name: Run help commands
      run: |
        python examples/simple_worker_client.py --help
    
    - name: Quick functionality test
      run: |
        # Test that the worker can at least parse arguments and show test info
        python examples/simple_worker_client.py --device-id ci-test --test --main-host 127.0.0.1 || echo "Test mode completed"